#!/usr/bin/env python3
"""
Bibliography Sync - BBL file parser and bibliography synchronization utilities.

This module provides functions for:
- Parsing .bbl files to extract citation keys
- Extracting bibliography file references from LaTeX sources
- Reading and writing BibTeX files
- Parsing BibTeX entry fields
"""

import re
import shutil
import subprocess
from pathlib import Path
from typing import List, Optional


def read_bbl_file(bbl_path: Path) -> str:
    """Read .bbl file content.

    Args:
        bbl_path: Path to the .bbl file

    Returns:
        Content of the .bbl file as string

    Raises:
        FileNotFoundError: If .bbl file does not exist
        OSError: If file cannot be read
    """
    return bbl_path.read_text(encoding='utf-8')


def parse_bbl_citations(bbl_path: Path) -> List[str]:
    """Extract citation keys from .bbl file in order.

    This function parses the bibliography output (.bbl) file generated by LaTeX
    and extracts the citation keys in the order they appear. It supports multiple
    formats generated by different LaTeX backends (BibTeX, BibLaTeX, etc.).

    Args:
        bbl_path: Path to the .bbl file

    Returns:
        List of citation keys in order of appearance

    Raises:
        FileNotFoundError: If .bbl file does not exist
    """
    content = read_bbl_file(bbl_path)

    citations = []

    # Pattern 1: \bibitem[{display}]{key} - BibTeX with optional display label
    # Example: \bibitem[Author(2021)]{smith2021}
    pattern1 = r'\\bibitem\[[^]]*\]\{([^\}]+)\}'

    # Pattern 2: \bibitem{key} - Standard BibTeX
    # Example: \bibitem{smith2021}
    pattern2 = r'\\bibitem\{([^\}]+)\}'

    # Pattern 3: BibLaTeX entry format
    # Example: \entry{smith2021}{article}{...}
    pattern3 = r'\\entry\{([^\}]+)\}\{'

    # Pattern 4: \bibitem[\key]{key} - BibLaTeX with escaped key
    # Example: \bibitem[\key]{smith2021}
    pattern4 = r'\\bibitem\[\\key\]\{([^\}]+)\}'

    # Pattern 5: \setentrytag{key} - Some BibLaTeX variants
    # Example: \setentrytag{smith2021}
    pattern5 = r'\\setentrytag\{([^\}]+)\}'

    # Combine patterns - try them in order of specificity
    # Pattern 1 first (with display label), then pattern 2 (standard)
    combined_pattern = f'{pattern1}|{pattern2}|{pattern3}|{pattern4}|{pattern5}'

    matches = re.finditer(combined_pattern, content)
    for match in matches:
        # The key is in the first non-None group
        key = next(g for g in match.groups() if g is not None)
        # Clean up the key
        key = key.strip()
        citations.append(key)

    return citations


def read_tex_file(tex_path: Path) -> str:
    """Read .tex file content.

    Args:
        tex_path: Path to the .tex file

    Returns:
        Content of the .tex file as string

    Raises:
        FileNotFoundError: If .tex file does not exist
        OSError: If file cannot be read
    """
    return tex_path.read_text(encoding='utf-8')


def extract_bibliography_files(tex_content: str) -> List[str]:
    """Extract bibliography files from LaTeX content.

    Supports multiple bibliography declaration formats:
    - \bibliography{ref1,ref2} - Standard BibTeX
    - \addbibresource{ref.bib} - BibLaTeX (comma-separated)
    - \addbibresource[datatype=bibtex]{ref.bib} - BibLaTeX with options

    Args:
        tex_content: LaTeX file content

    Returns:
        List of bibliography file names (without extension unless specified)
    """
    bibliography_files = []

    # Pattern 1: Standard BibTeX \bibliography{ref1,ref2,...}
    bib_pattern = r'\\bibliography\{([^}]+)\}'
    for match in re.finditer(bib_pattern, tex_content, re.IGNORECASE):
        files_str = match.group(1)
        # Split by comma and strip whitespace
        files = [f.strip() for f in files_str.split(',')]
        bibliography_files.extend(files)

    # Pattern 2: BibLaTeX \addbibresource[options]{file} or \addbibresource{file}
    addbib_pattern = r'\\addbibresource(?:\[[^\]]*\])?\{([^}]+)\}'
    for match in re.finditer(addbib_pattern, tex_content, re.IGNORECASE):
        files_str = match.group(1)
        # Split by comma and strip whitespace
        files = [f.strip() for f in files_str.split(',')]
        bibliography_files.extend(files)

    # Remove duplicates while preserving order
    seen = set()
    unique_files = []
    for f in bibliography_files:
        if f not in seen:
            seen.add(f)
            unique_files.append(f)

    return unique_files


def parse_bibtex_field(content: str, field: str, start: str = '{') -> Optional[str]:
    """Parse a specific field from BibTeX entry content.

    This function extracts the value of a specific field from a BibTeX entry,
    handling various formatting including nested braces.

    Args:
        content: BibTeX entry content (e.g., the portion after @article{key,)
        field: Field name to extract (e.g., 'author', 'title', 'year')
        start: Start delimiter for the field value (default: '{')

    Returns:
        Field value as string, or None if field not found

    Examples:
        >>> content = 'author = {Smith, John}, title = {Paper Title}, year = 2021'
        >>> parse_bibtex_field(content, 'author')
        'Smith, John'
        >>> parse_bibtex_field(content, 'missing')
        None
    """
    # Build pattern based on delimiter
    if start == '{':
        # Match field = {value} with balanced braces
        # Handle nested braces properly
        field_start = rf'{field}\s*=\s*\{{'

        # Find the starting position
        start_match = re.search(field_start, content, re.IGNORECASE)
        if not start_match:
            return None

        # Find the end by balancing braces
        start_pos = start_match.end()
        brace_depth = 1
        i = start_pos
        while i < len(content) and brace_depth > 0:
            if content[i] == '{':
                brace_depth += 1
            elif content[i] == '}':
                brace_depth -= 1
            i += 1

        value = content[start_pos:i - 1].strip()

    elif start == '"':
        # Match field = "value"
        pattern = rf'{field}\s*=\s*"([^"]*)"'
        match = re.search(pattern, content, re.IGNORECASE)
        if not match:
            return None
        value = match.group(1).strip()
    else:
        return None

    # Clean up whitespace
    value = re.sub(r'\s+', ' ', value)

    return value if value else None


def read_bibtex(bib_path: Path) -> List[dict]:
    """Read BibTeX file and return list of entries.

    Each entry is represented as a dictionary with:
    - 'type': Entry type (article, book, inproceedings, etc.)
    - 'key': Citation key
    - 'content': Full entry content as string

    Args:
        bib_path: Path to the BibTeX file

    Returns:
        List of BibTeX entry dictionaries

    Raises:
        FileNotFoundError: If BibTeX file does not exist
        OSError: If file cannot be read
    """
    content = bib_path.read_text(encoding='utf-8')

    # Remove comments before parsing
    content = re.sub(r'%.*$', '', content, flags=re.MULTILINE)

    # Pattern to match BibTeX entries
    # This is a more robust pattern that handles nested braces
    # @type{key, ...} or @type (key, ...)
    entry_pattern = r'@(\w+)\s*(?:\{|\(\{?)\s*(\w+)\s*,'

    entries = []
    # Find all entry start positions
    for match in re.finditer(entry_pattern, content):
        entry_type = match.group(1)
        entry_key = match.group(2)
        entry_start = match.start()

        # Find the opening brace of the entry
        open_brace = content.find('{', entry_start)
        if open_brace == -1:
            continue

        # Count braces from the opening brace of the entry
        brace_depth = 1
        i = open_brace + 1
        while i < len(content) and brace_depth > 0:
            if content[i] == '{':
                brace_depth += 1
            elif content[i] == '}':
                brace_depth -= 1
            i += 1

        # Extract the full entry content (excluding @type{key,)
        # Find the comma after the key within the entry
        key_end = match.end()  # Position after the comma following the key
        if key_end < open_brace:
            # The comma is before the opening brace, use it
            entry_content = content[key_end:i - 1].strip()
        else:
            # Find the comma after the opening brace
            after_key = content.find(',', open_brace)
            if after_key != -1 and after_key < i:
                entry_content = content[after_key + 1:i - 1].strip()
            else:
                entry_content = content[open_brace + 1:i - 1].strip()

        entries.append({
            'type': entry_type.lower(),
            'key': entry_key,
            'content': entry_content,
        })

    return entries


def write_bibtex(entries: List[dict], output_path: Path) -> None:
    """Write entries to BibTeX file.

    Each entry dict should have:
    - 'type': Entry type (article, book, etc.)
    - 'key': Citation key
    - 'content': Entry content (fields and values)

    Args:
        entries: List of entry dictionaries
        output_path: Path to output BibTeX file

    Raises:
        OSError: If file cannot be written
        ValueError: If entry is missing required fields
    """
    lines = []

    for entry in entries:
        if 'type' not in entry or 'key' not in entry:
            raise ValueError("Entry must have 'type' and 'key' fields")

        entry_type = entry['type']
        entry_key = entry['key']
        content = entry.get('content', '')

        # Format: @type{key,
        # content
        # }
        lines.append(f'@{entry_type}{{{entry_key},')
        lines.append(content)

        # Ensure proper formatting
        if not content.endswith('}'):
            lines.append('}')
        else:
            # Content already ends with closing brace
            pass

        lines.append('')  # Empty line between entries

    output_path.write_text('\n'.join(lines), encoding='utf-8')


def compile_latex(tex_path: Path) -> Optional[Path]:
    """Compile a .tex file using available LaTeX compilers.

    This function tries multiple LaTeX compilers in order (pdflatex, xelatex,
    lualatex) and returns the path to the generated .bbl file if successful.

    Args:
        tex_path: Path to the .tex file to compile

    Returns:
        Path to the generated .bbl file if compilation succeeds,
        None if all compilers fail
    """
    # Convert to Path object if string is passed
    if not isinstance(tex_path, Path):
        tex_path = Path(tex_path)

    # List of LaTeX compilers to try, in order of preference
    compilers = ['pdflatex', 'xelatex', 'lualatex']

    for compiler in compilers:
        # Check if compiler is available
        if shutil.which(compiler) is None:
            continue

        try:
            # Run the compiler with -interaction=nonstopmode to avoid blocking
            # Capture output to suppress console noise
            result = subprocess.run(
                [compiler, '-interaction=nonstopmode', str(tex_path)],
                capture_output=True,
                text=True,
                cwd=tex_path.parent
            )

            # Check if compilation was successful (return code 0)
            if result.returncode == 0:
                # Check if .bbl file exists
                bbl_path = tex_path.with_suffix('.bbl')
                if bbl_path.exists():
                    return bbl_path

        except (subprocess.SubprocessError, OSError):
            # Try the next compiler if this one fails
            continue

    # All compilers failed
    return None
