#!/usr/bin/env python3
"""
Bibliography Sync - BBL file parser and bibliography synchronization utilities.

This module provides functions for:
- Parsing .bbl files to extract citation keys
- Extracting bibliography file references from LaTeX sources
"""

import re
import shutil
import subprocess
from pathlib import Path
from typing import List, Optional

from bib_utils import read_bibtex, write_bibtex


def read_bbl_file(bbl_path: Path) -> str:
    """Read .bbl file content.

    Args:
        bbl_path: Path to the .bbl file

    Returns:
        Content of the .bbl file as string

    Raises:
        FileNotFoundError: If .bbl file does not exist
        OSError: If file cannot be read
    """
    return bbl_path.read_text(encoding='utf-8')


def parse_bbl_citations(bbl_path: Path) -> List[str]:
    """Extract citation keys from .bbl file in order.

    This function parses the bibliography output (.bbl) file generated by LaTeX
    and extracts the citation keys in the order they appear. It supports multiple
    formats generated by different LaTeX backends (BibTeX, BibLaTeX, etc.).

    Args:
        bbl_path: Path to the .bbl file

    Returns:
        List of citation keys in order of appearance

    Raises:
        FileNotFoundError: If .bbl file does not exist
    """
    content = read_bbl_file(bbl_path)

    citations = []

    # Pattern 1: \bibitem[{display}]{key} - BibTeX with optional display label
    # Example: \bibitem[Author(2021)]{smith2021}
    pattern1 = r'\\bibitem\[[^]]*\]\{([^\}]+)\}'

    # Pattern 2: \bibitem{key} - Standard BibTeX
    # Example: \bibitem{smith2021}
    pattern2 = r'\\bibitem\{([^\}]+)\}'

    # Pattern 3: BibLaTeX entry format
    # Example: \entry{smith2021}{article}{...}
    pattern3 = r'\\entry\{([^\}]+)\}\{'

    # Pattern 4: \bibitem[\key]{key} - BibLaTeX with escaped key
    # Example: \bibitem[\key]{smith2021}
    pattern4 = r'\\bibitem\[\\key\]\{([^\}]+)\}'

    # Pattern 5: \setentrytag{key} - Some BibLaTeX variants
    # Example: \setentrytag{smith2021}
    pattern5 = r'\\setentrytag\{([^\}]+)\}'

    # Combine patterns - try them in order of specificity
    # Pattern 1 first (with display label), then pattern 2 (standard)
    combined_pattern = f'{pattern1}|{pattern2}|{pattern3}|{pattern4}|{pattern5}'

    matches = re.finditer(combined_pattern, content)
    for match in matches:
        # The key is in the first non-None group
        key = next(g for g in match.groups() if g is not None)
        # Clean up the key
        key = key.strip()
        citations.append(key)

    return citations


def read_tex_file(tex_path: Path) -> str:
    """Read .tex file content.

    Args:
        tex_path: Path to the .tex file

    Returns:
        Content of the .tex file as string

    Raises:
        FileNotFoundError: If .tex file does not exist
        OSError: If file cannot be read
    """
    return tex_path.read_text(encoding='utf-8')


def extract_bibliography_files(tex_content: str) -> List[str]:
    """Extract bibliography files from LaTeX content.

    Supports multiple bibliography declaration formats:
    - \bibliography{ref1,ref2} - Standard BibTeX
    - \addbibresource{ref.bib} - BibLaTeX (comma-separated)
    - \addbibresource[datatype=bibtex]{ref.bib} - BibLaTeX with options

    Args:
        tex_content: LaTeX file content

    Returns:
        List of bibliography file names (without extension unless specified)
    """
    bibliography_files = []

    # Pattern 1: Standard BibTeX \bibliography{ref1,ref2,...}
    bib_pattern = r'\\bibliography\{([^}]+)\}'
    for match in re.finditer(bib_pattern, tex_content, re.IGNORECASE):
        files_str = match.group(1)
        # Split by comma and strip whitespace
        files = [f.strip() for f in files_str.split(',')]
        bibliography_files.extend(files)

    # Pattern 2: BibLaTeX \addbibresource[options]{file} or \addbibresource{file}
    addbib_pattern = r'\\addbibresource(?:\[[^\]]*\])?\{([^}]+)\}'
    for match in re.finditer(addbib_pattern, tex_content, re.IGNORECASE):
        files_str = match.group(1)
        # Split by comma and strip whitespace
        files = [f.strip() for f in files_str.split(',')]
        bibliography_files.extend(files)

    # Remove duplicates while preserving order
    seen = set()
    unique_files = []
    for f in bibliography_files:
        if f not in seen:
            seen.add(f)
            unique_files.append(f)

    return unique_files


def parse_bibtex_field(content: str, field: str, start: str = '{') -> Optional[str]:
    """Parse a specific field from BibTeX entry content.

    This function extracts the value of a specific field from a BibTeX entry,
    handling various formatting including nested braces.

    Args:
        content: BibTeX entry content (e.g., the portion after @article{key,)
        field: Field name to extract (e.g., 'author', 'title', 'year')
        start: Start delimiter for the field value (default: '{')

    Returns:
        Field value as string, or None if field not found

    Examples:
        >>> content = 'author = {Smith, John}, title = {Paper Title}, year = 2021'
        >>> parse_bibtex_field(content, 'author')
        'Smith, John'
        >>> parse_bibtex_field(content, 'missing')
        None
    """
    # Build pattern based on delimiter
    if start == '{':
        # Match field = {value} with balanced braces
        # Handle nested braces properly
        field_start = rf'{field}\s*=\s*\{{'

        # Find the starting position
        start_match = re.search(field_start, content, re.IGNORECASE)
        if not start_match:
            return None

        # Find the end by balancing braces
        start_pos = start_match.end()
        brace_depth = 1
        i = start_pos
        while i < len(content) and brace_depth > 0:
            if content[i] == '{':
                brace_depth += 1
            elif content[i] == '}':
                brace_depth -= 1
            i += 1

        value = content[start_pos:i - 1].strip()

    elif start == '"':
        # Match field = "value"
        pattern = rf'{field}\s*=\s*"([^"]*)"'
        match = re.search(pattern, content, re.IGNORECASE)
        if not match:
            return None
        value = match.group(1).strip()
    else:
        return None

    # Clean up whitespace
    value = re.sub(r'\s+', ' ', value)

    return value if value else None


def compile_latex(tex_path: Path) -> Optional[Path]:
    """Compile a .tex file using available LaTeX compilers.

    This function tries multiple LaTeX compilers in order (pdflatex, xelatex,
    lualatex) and returns the path to the generated .bbl file if successful.

    Args:
        tex_path: Path to the .tex file to compile

    Returns:
        Path to the generated .bbl file if compilation succeeds,
        None if all compilers fail
    """
    # Convert to Path object if string is passed
    if not isinstance(tex_path, Path):
        tex_path = Path(tex_path)

    # List of LaTeX compilers to try, in order of preference
    compilers = ['pdflatex', 'xelatex', 'lualatex']

    for compiler in compilers:
        # Check if compiler is available
        if shutil.which(compiler) is None:
            continue

        try:
            # Run the compiler with -interaction=nonstopmode to avoid blocking
            # Capture output to suppress console noise
            result = subprocess.run(
                [compiler, '-interaction=nonstopmode', str(tex_path)],
                capture_output=True,
                text=True,
                cwd=tex_path.parent
            )

            # Check if compilation was successful (return code 0)
            if result.returncode == 0:
                # Check if .bbl file exists
                bbl_path = tex_path.with_suffix('.bbl')
                if bbl_path.exists():
                    return bbl_path

        except (subprocess.SubprocessError, OSError):
            # Try the next compiler if this one fails
            continue

    # All compilers failed
    return None


def extract_doi_from_bib(bib_path: Path, key: str) -> Optional[str]:
    """Extract DOI from original .bib file for a given citation key.

    This function reads a BibTeX file and extracts the DOI field for a specific
    citation key. It handles various DOI field formats and positions.

    Args:
        bib_path: Path to the BibTeX file
        key: Citation key to search for

    Returns:
        DOI string if found, None otherwise

    Raises:
        FileNotFoundError: If BibTeX file does not exist
        OSError: If file cannot be read
    """
    content = bib_path.read_text(encoding='utf-8')

    # Find the entry for the given key
    # Pattern: @type{key, or @type (key,
    entry_pattern = r'@(\w+)\s*(?:\{|\(\{?)\s*\s*' + re.escape(key) + r'\s*,'

    entry_match = re.search(entry_pattern, content)
    if not entry_match:
        return None

    # Find the opening brace of the entry
    entry_start = entry_match.start()
    open_brace = content.find('{', entry_start)
    if open_brace == -1:
        return None

    # Find the closing brace of the entry
    brace_depth = 1
    i = open_brace + 1
    while i < len(content) and brace_depth > 0:
        if content[i] == '{':
            brace_depth += 1
        elif content[i] == '}':
            brace_depth -= 1
        i += 1

    entry_content = content[open_brace + 1:i - 1]

    # Extract DOI field
    # Handle various formats: doi = {value}, doi = "value", DOI = {value}, etc.
    doi_patterns = [
        r'doi\s*=\s*\{([^}]+)\}',
        r'doi\s*=\s*"([^"]+)"',
        r'DOI\s*=\s*\{([^}]+)\}',
        r'DOI\s*=\s*"([^"]+)"',
    ]

    for pattern in doi_patterns:
        match = re.search(pattern, entry_content, re.IGNORECASE)
        if match:
            doi = match.group(1).strip()
            # Clean up common DOI prefixes
            if doi.startswith('http'):
                # Extract DOI from URL
                # Format: https://doi.org/10.xxxx/xxxxx
                url_match = re.search(r'doi\.org/(10\.[^/\s]+/[^\s]+)', doi)
                if url_match:
                    return url_match.group(1)
            elif doi.startswith('doi:'):
                return doi[4:].strip()
            return doi

    return None


def papis_add(doi: str) -> Optional[subprocess.CompletedProcess]:
    """Call papis add command with specified DOI.

    This function executes the papis add command to add a paper to the
    papis library using its DOI.

    Args:
        doi: DOI string to add

    Returns:
        subprocess.CompletedProcess if papis is available, None otherwise
    """
    if shutil.which('papis') is None:
        return None

    try:
        result = subprocess.run(
            ['papis', 'add', '--from', 'doi', doi],
            capture_output=True,
            text=True
        )
        return result
    except (subprocess.SubprocessError, OSError):
        return None


def update_entry_cite_order(bib_path: Path, key: str, order: str) -> None:
    """Add cite_order field to BibTeX entry.

    This function adds or updates the cite_order field for a specific entry
    without rewriting the entire entry. It uses string manipulation to
    preserve the original formatting.

    Args:
        bib_path: Path to the BibTeX file
        key: Citation key to update
        order: Citation order value to set

    Raises:
        FileNotFoundError: If BibTeX file does not exist
        ValueError: If entry not found
        OSError: If file cannot be read or written
    """
    content = bib_path.read_text(encoding='utf-8')

    # Find the entry for the given key
    entry_pattern = r'@(\w+)\s*(?:\{|\(\{?)\s*\s*' + re.escape(key) + r'\s*,'

    entry_match = re.search(entry_pattern, content)
    if not entry_match:
        raise ValueError(f"Entry '{key}' not found in BibTeX file")

    # Find the opening brace of the entry
    entry_start = entry_match.start()
    open_brace = content.find('{', entry_start)
    if open_brace == -1:
        raise ValueError(f"Invalid entry format for '{key}'")

    # Find the closing brace of the entry
    brace_depth = 1
    i = open_brace + 1
    while i < len(content) and brace_depth > 0:
        if content[i] == '{':
            brace_depth += 1
        elif content[i] == '}':
            brace_depth -= 1
        i += 1

    entry_close = i - 1

    # Extract the entry content (after the opening brace, before closing brace)
    entry_content = content[open_brace + 1:entry_close]

    # Check if cite_order already exists
    cite_order_pattern = r'cite_order\s*=\s*'
    if re.search(cite_order_pattern, entry_content, re.IGNORECASE):
        # Update existing cite_order - use the approach from remove_entry_field
        # Find the cite_order field
        field_match = re.search(cite_order_pattern, entry_content, re.IGNORECASE)
        if field_match:
            field_start = field_match.start()

            # Find where the value ends
            delimiter = content[open_brace + 1 + field_match.end():open_brace + 1 + field_match.end() + 1]
            if delimiter == '{':
                # Find balanced braces
                value_start = open_brace + 1 + field_match.end() + 1
                brace_depth = 1
                i = value_start
                while i < len(content) and brace_depth > 0:
                    if content[i] == '{':
                        brace_depth += 1
                    elif content[i] == '}':
                        brace_depth -= 1
                    i += 1
                value_end = i
            else:
                # Quote delimited
                value_start = open_brace + 1 + field_match.end() + 1
                value_end = content.find('"', value_start)
                if value_end == -1:
                    value_end = entry_close
                else:
                    value_end += 1

            # Find trailing comma and whitespace
            i = value_end
            while i < len(content) and (content[i].isspace() or content[i] == ','):
                i += 1

            # Construct new content
            before = content[:open_brace + 1 + field_start]
            after = content[i:]
            new_cite_order = f'cite_order = {{{order}}},'
            new_content = before + new_cite_order + after
            bib_path.write_text(new_content, encoding='utf-8')
    else:
        # Add new cite_order field - insert after the first complete field
        # Find the comma after the key
        key_end = content.find(',', open_brace)
        if key_end == -1 or key_end > entry_close:
            raise ValueError(f"Invalid entry format for '{key}'")

        # Find a good insertion point
        # Look for the first complete field (field_name = value,)
        after_key = content[key_end + 1:entry_close]

        # Pattern to match a complete field: word = {value} or word = "value"
        # We need to handle balanced braces for brace-delimited values
        insert_pos = key_end + 1  # Default: insert right after the key comma

        # Try to find the first field and insert after it
        field_start = re.search(r'\w+\s*=\s*[{"]', after_key)
        if field_start:
            start = field_start.start()
            # Find the end of this field
            delimiter = after_key[start + len(field_start.group(0)) - 1]
            value_start = start + len(field_start.group(0))

            if delimiter == '{':
                # Find balanced braces
                brace_depth = 1
                i = value_start
                while i < len(after_key) and brace_depth > 0:
                    if after_key[i] == '{':
                        brace_depth += 1
                    elif after_key[i] == '}':
                        brace_depth -= 1
                    i += 1
                field_end = i
            else:
                # Quote delimited
                field_end = after_key.find('"', value_start)
                if field_end == -1:
                    field_end = len(after_key)
                else:
                    field_end += 1

            # Find the trailing comma
            i = field_end
            while i < len(after_key) and (after_key[i].isspace() or after_key[i] == ','):
                i += 1

            if i < len(after_key):
                insert_pos = key_end + 1 + i

        # Insert cite_order
        cite_order_line = f'\n  cite_order = {{{order}}},'
        new_content = content[:insert_pos] + cite_order_line + content[insert_pos:]
        bib_path.write_text(new_content, encoding='utf-8')


def remove_entry_field(bib_path: Path, key: str, field: str) -> None:
    """Remove a field from BibTeX entry.

    This function removes a specific field from a BibTeX entry, handling
    both brace and quote delimiters.

    Args:
        bib_path: Path to the BibTeX file
        key: Citation key to update
        field: Field name to remove

    Raises:
        FileNotFoundError: If BibTeX file does not exist
        ValueError: If entry not found
        OSError: If file cannot be read or written
    """
    content = bib_path.read_text(encoding='utf-8')

    # Find the entry for the given key
    entry_pattern = r'@(\w+)\s*(?:\{|\(\{?)\s*\s*' + re.escape(key) + r'\s*,'

    entry_match = re.search(entry_pattern, content)
    if not entry_match:
        raise ValueError(f"Entry '{key}' not found in BibTeX file")

    # Find the opening brace of the entry
    entry_start = entry_match.start()
    open_brace = content.find('{', entry_start)
    if open_brace == -1:
        raise ValueError(f"Invalid entry format for '{key}'")

    # Find the closing brace of the entry
    brace_depth = 1
    i = open_brace + 1
    while i < len(content) and brace_depth > 0:
        if content[i] == '{':
            brace_depth += 1
        elif content[i] == '}':
            brace_depth -= 1
        i += 1

    entry_close = i - 1

    # Extract the entry content
    entry_content = content[open_brace + 1:entry_close]

    # Find and remove the field by parsing
    # First, try to find the field pattern
    # Pattern: field_name = {value} or field_name = "value"
    field_start_pattern = field + r'\s*=\s*[{"]'
    field_match = re.search(field_start_pattern, entry_content, re.IGNORECASE)

    if field_match:
        # Field found, need to remove it
        field_start = field_match.start()

        # Find where the value ends
        delimiter = entry_content[field_match.end() - 1]  # { or "
        value_start = field_match.end()

        if delimiter == '{':
            # Need to find balanced braces
            brace_depth = 1
            i = value_start
            while i < len(entry_content) and brace_depth > 0:
                if entry_content[i] == '{':
                    brace_depth += 1
                elif entry_content[i] == '}':
                    brace_depth -= 1
                i += 1
            value_end = i
        else:
            # Quote delimited - find the closing quote
            value_end = entry_content.find('"', value_start)
            if value_end == -1:
                value_end = len(entry_content)
            else:
                value_end += 1  # Include the closing quote

        # Find the trailing comma and whitespace
        i = value_end
        while i < len(entry_content) and (entry_content[i].isspace() or entry_content[i] == ','):
            i += 1

        # Remove the field
        new_entry_content = entry_content[:field_start] + entry_content[i:]
    else:
        # Field not found, return unchanged
        new_entry_content = entry_content

    # Clean up leading whitespace and comma
    new_entry_content = re.sub(r'^\s*,?\s*', '', new_entry_content)

    # Reconstruct the content
    new_content = content[:open_brace + 1] + new_entry_content + content[entry_close:]

    bib_path.write_text(new_content, encoding='utf-8')


def sort_bibtex_by_cite_order(bib_path: Path) -> List[dict]:
    """Sort BibTeX entries by cite_order field and rewrite file.

    This function reads a BibTeX file, sorts entries by their cite_order field,
    and writes the sorted entries back to the file. Entries without a
    cite_order field are placed at the end.

    Args:
        bib_path: Path to the BibTeX file

    Returns:
        List of entry dictionaries in sorted order

    Raises:
        FileNotFoundError: If BibTeX file does not exist
        OSError: If file cannot be read or written
    """
    entries = read_bibtex(bib_path)

    # Extract cite_order from each entry
    for entry in entries:
        cite_order = parse_bibtex_field(entry['content'], 'cite_order')
        entry['cite_order'] = cite_order

    # Sort by cite_order, putting entries without cite_order at the end
    sorted_entries = sorted(
        entries,
        key=lambda e: int(e.get('cite_order', '9999')) if e.get('cite_order') else 9999
    )

    # Write sorted entries back
    write_bibtex(sorted_entries, bib_path)

    return sorted_entries


def sync_references(tex_path: Path, bib_path: Path, papis_bib_path: Path) -> None:
    """Main sync function. Tracks citation order and fetches missing references.

    This function:
    1. Compiles LaTeX to generate .bbl file
    2. Parses cited keys from .bbl file
    3. Reads papis.bib entries
    4. Finds missing references
    5. For each missing reference: tries to extract DOI from original .bib file,
       calls papis to fetch, or prompts user for input
    6. Adds cite_order field to cited entries
    7. Removes cite_order field from uncited entries
    8. Sorts papis.bib by cite_order
    9. Writes updated entries to papis.bib

    Args:
        tex_path: Path to the .tex file to compile
        bib_path: Path to the original BibTeX file (used for DOI extraction)
        papis_bib_path: Path to the papis.bib file to update

    Raises:
        FileNotFoundError: If required files do not exist
        OSError: If files cannot be read or written
    """
    # 1. Compile tex to get bbl
    bbl_path = compile_latex(tex_path)
    if not bbl_path or not bbl_path.exists():
        print(f"Warning: Could not compile {tex_path}")
        return

    # 2. Parse cited keys from .bbl file
    cited_keys = parse_bbl_citations(bbl_path)

    # 3. Read papis.bib entries
    papis_entries = read_bibtex(papis_bib_path)
    papis_keys = set(entry['key'] for entry in papis_entries)

    # 4. Find missing references
    missing = set(cited_keys) - papis_keys

    # 5. For each missing reference, try to fetch it
    for key in missing:
        # Try to extract DOI from original .bib file
        doi = extract_doi_from_bib(bib_path, key)
        if doi:
            # Call papis to fetch the missing reference
            result = papis_add(doi)
            if result and result.returncode == 0:
                print(f"Fetching missing reference: {key}")
            else:
                print(f"Warning: Failed to fetch {key} with DOI: {doi}")
        else:
            # Prompt user for input
            print(f"Warning: No DOI found for {key}")
            print(f"Please provide a DOI, URL, or other identifier for '{key}'")
            user_input = input("Enter DOI/URL, or press Enter to skip: ").strip()
            if user_input:
                result = papis_add(user_input)
                if result and result.returncode == 0:
                    print(f"Successfully fetched reference for '{key}'")
                else:
                    print(f"Warning: Failed to fetch {key}")

    # Re-read papis.bib entries after potential additions
    papis_entries = read_bibtex(papis_bib_path)

    # 6. Add cite_order field to cited entries
    for idx, key in enumerate(cited_keys, start=1):
        try:
            update_entry_cite_order(papis_bib_path, key, str(idx))
        except ValueError as e:
            print(f"Warning: {e}")

    # 7. Remove cite_order field from uncited entries
    for entry in papis_entries:
        if entry['key'] not in cited_keys:
            try:
                remove_entry_field(papis_bib_path, entry['key'], 'cite_order')
            except ValueError as e:
                print(f"Warning: {e}")

    # 8. Sort and export papis.bib by cite_order
    sort_bibtex_by_cite_order(papis_bib_path)
